ExtendRealityLtd/Tilia.Interactions.Controllables.Unity

- Runtime/Prefabs/PhysicsJoint/Interactions.AngularJointDrive.prefab
- Runtime/Prefabs/PhysicsJoint/Interactions.LinearJointDrive.prefab
- Runtime/Prefabs/Transform/Interactions.AngularTransformDrive.prefab
- Runtime/Prefabs/Transform/Interactions.LinearTransformDrive.prefab
- Runtime/SharedResources/NestedPrefabs/Drive.ValueEvents.prefab
- Runtime/SharedResources/Scripts/AngularDriver/AngularJointDrive.cs
- Runtime/SharedResources/Scripts/AngularDriver/AngularTransformDrive.cs
- Runtime/SharedResources/Scripts/Driver/Drive.cs
- Runtime/SharedResources/Scripts/Driver/DriveFacade.cs
- Runtime/SharedResources/Scripts/LinearDriver/LinearJointDrive.cs
The Initial Target Value allows a drive to be given an initial
normalized value to drive the control to when it is first enabled
without any events being triggered.
This is useful for starting controls at a certain point as by default
they all start in their central position due to the way Unity works
out drive extends for joints.
> feat(Drive): provide initial target value for drive to start at

- Runtime/SharedResources/Scripts/Driver/Drive.cs
- Runtime/SharedResources/Scripts/Driver/DriveFacade.cs
The new InitialTargetValueReached event is emitted when the initial
target value is reached and is useful for setting up initial
configuration as by default the initial target value process will not
emit any events even when the target value is reached so this new
InitialTargetValueReached event can be used to set up any initial
state required by the control.
> feat(Drive): emit event when the initial target value is reached

- Runtime/SharedResources/Scripts/Driver/Drive.cs
Using a drive speed that is too high causes problems with Unity joints
and can cause them to break their restrictions.
Instead of using a float max value, it now uses just a high value that
is fast enough to not notice but not fast enough to break the Unity
joints system.
Whilst 5000f seems like a magic number, it's just a number that was
decided that fell into the category of not breaking things but being
fast enough to not notice.
> fix(Drive): use actual value for initial start drive speed

- Runtime/SharedResources/Scripts/AngularDriver/AngularTransformDrive.cs
- Runtime/SharedResources/Scripts/LinearDriver/LinearTransformDrive.cs
- package.json
The Interactables namespace changed in version 1.9.0 of the
Interactables package, so it has been updated accordingly.
> fix(Interactables): update Interactables namespace to latest

- .dependabot/config.yml
- Documentation/API/AngularDriver/AngularDrive.md
- Documentation/API/AngularDriver/AngularDriveFacade.md
- Documentation/API/AngularDriver/AngularJointDrive.md
- Documentation/API/AngularDriver/AngularTransformDrive.md
- Documentation/API/Driver/Drive-2.md
- Documentation/API/Driver/DriveFacade-2.md
- Documentation/API/LinearDriver/LinearDrive.md
- Documentation/API/LinearDriver/LinearDriveFacade.md
- Documentation/API/LinearDriver/LinearJointDrive.md
- Documentation/API/LinearDriver/LinearTransformDrive.md
- Runtime/Prefabs/PhysicsJoint/Interactions.AngularJointDrive.prefab
- Runtime/Prefabs/PhysicsJoint/Interactions.LinearJointDrive.prefab
- Runtime/Prefabs/Transform/Interactions.AngularTransformDrive.prefab
- Runtime/Prefabs/Transform/Interactions.LinearTransformDrive.prefab
- Runtime/SharedResources/Scripts/AngularDriver/AngularDrive.cs
- Runtime/SharedResources/Scripts/AngularDriver/AngularDriveFacade.cs
- Runtime/SharedResources/Scripts/Driver/Drive.cs
- Runtime/SharedResources/Scripts/Driver/DriveFacade.cs
A number of properties cannot be changed via UnityEvents because
they are non-standard data types, so methods have been added that
allow for these data types to be changed.
A small fix for the DriveLimits not being updated has been added
and the Setup code has been refactored so the individual setup
elements can now be run individually if need be.
Also, now when the DriveAxis is changed, it will reset the rotation
on the axis as otherwise the rotations cause adverse effects. It
needs looking into further in the future to see if the rotational
data can be kept when switching axes as this would be a nice feature.
> feat(Driver): add methods for properties in UnityEvents

- Documentation/API/AngularDriver/AngularDrive.md
- Documentation/API/AngularDriver/AngularJointDrive.md
- Documentation/API/AngularDriver/AngularTransformDrive.md
- Documentation/API/Driver/Drive-2.md
- Documentation/API/LinearDriver/LinearDrive.md
- Documentation/API/LinearDriver/LinearJointDrive.md
- Documentation/API/LinearDriver/LinearTransformDrive.md
- Runtime/Prefabs/PhysicsJoint/Interactions.AngularJointDrive.prefab
- Runtime/Prefabs/PhysicsJoint/Interactions.LinearJointDrive.prefab
- Runtime/Prefabs/Transform/Interactions.AngularTransformDrive.prefab
- Runtime/Prefabs/Transform/Interactions.LinearTransformDrive.prefab
- Runtime/SharedResources/Scripts/AngularDriver/AngularDrive.cs
- Runtime/SharedResources/Scripts/Driver/Drive.cs
- Runtime/SharedResources/Scripts/Driver/DriveFacade.cs
The AngularDrive ResetRotations was causing the MoveToTargetValue
functionality to break because it was always resetting the drive
everytime the target value changed. This has been fixed by reworking
the Reset concept into the core Drive class and having the ability
of only calling ResetDrive the first time SetUp is called and then it
won't call Reset again until a manual intervention occurs.
> fix(Drive): rework the drive reset functionality

- Runtime/SharedResources/Scripts/Driver/DriveFacade.cs
The SetDriveAxis method now uses the Zinnia EnumExtensions
helper method to set the value of the enum by the index instead of
repeating the same logic.
> refactor(Facade): use extension method to set enum value

- Documentation/API/AngularDriver/AngularDrive.md
- Documentation/API/AngularDriver/AngularJointDrive.md
- Documentation/API/AngularDriver/AngularTransformDrive.md
- Documentation/API/Driver/Drive-2.md
- Documentation/API/LinearDriver/LinearDrive.md
- Documentation/API/LinearDriver/LinearJointDrive.md
- Documentation/API/LinearDriver/LinearTransformDrive.md
- Runtime/Prefabs/Transform/Interactions.AngularTransformDrive.prefab
- Runtime/SharedResources/Scripts/Driver/Drive.cs
The IntialDriveValueSpeed is now a public changable property rather
than a protected constant field so it can be adapted to suit different
requirements.
The AngularTransformDrive did not work well at such a high speed so
it has now been reduced to make it work correctly using this new
ability to publicly set the initial speed of the drive.
> fix(Drive): expose initial drive value speed as public property - fixes #55

- Runtime/SharedResources/Scripts/Driver/Drive.cs
The Step Value calculation was only working if the Step Increment value
was 1 because the final value should be multiplied by the Step
Increment value but it wasn't. It is now being multiplied correctly.
> fix(Drive): calculate correct step value for increments other than 1

- Documentation/API/AngularDriver/AngularDrive.md
- Documentation/API/AngularDriver/AngularJointDrive.md
- Documentation/API/AngularDriver/AngularTransformDrive.md
- Documentation/API/Driver/Drive-2.md
- Documentation/API/LinearDriver/LinearDrive.md
- Documentation/API/LinearDriver/LinearJointDrive.md
- Documentation/API/LinearDriver/LinearTransformDrive.md
- Runtime/SharedResources/Scripts/Driver/Drive.cs
There was an issue where the drive would not correctly run the process
code after it was disabled and re-enabled because the process code
relied on the fact that the drive would start in a central position
and move to a different location which would allow the process
mechanism to operate because the value delta has changed.
But upon disabling and re-enabling, the value of the button location
would be the same causing no process to occur which would then in turn
prevent the events from being emitted.
This fix just ensures that upon disable and re-enable the process at
least happens once to ensure the correct set up occurs.
> fix(Drive): process the drive correctly after disable and re-enable - fixes #76

- Documentation/API/AngularDriver/AngularDriveFacade.md
- Documentation/API/Driver/DriveFacade-2.md
- Documentation/API/LinearDriver/LinearDriveFacade.md
- Runtime/Prefabs/PhysicsJoint/Interactions.AngularJointDrive.prefab
- Runtime/Prefabs/PhysicsJoint/Interactions.LinearJointDrive.prefab
- Runtime/Prefabs/Transform/Interactions.AngularTransformDrive.prefab
- Runtime/Prefabs/Transform/Interactions.LinearTransformDrive.prefab
- Runtime/SharedResources/Scripts/Driver/DriveFacade.cs
The new ObjectReference property type has been added to the DriveFacade
to highlight some common nested object references on the facade
inspector, making it easier to find some of the nested required prefabs
for easier customisation.
> feat(DriveFacade): add object reference links to common nested objects - resolves #49

- Runtime/Prefabs/PhysicsJoint/Interactions.AngularJointDrive.prefab
- Runtime/Prefabs/PhysicsJoint/Interactions.LinearJointDrive.prefab
- Runtime/Prefabs/Transform/Interactions.AngularTransformDrive.prefab
- Runtime/Prefabs/Transform/Interactions.LinearTransformDrive.prefab
- Runtime/SharedResources/Scripts/AngularDriver/AngularDriveTag.cs
- Runtime/SharedResources/Scripts/AngularDriver/AngularDriveTag.cs.meta
- Runtime/SharedResources/Scripts/LinearDriver/LinearDriveTag.cs
- Runtime/SharedResources/Scripts/LinearDriver/LinearDriveTag.cs.meta
The drive elements have had a couple of tags and string identifiers
added to the parts of the drive that are reported upon collisions
such as the joint drives will report the joint GameObject and maybe
the Interactable GameObject, whereas the transform drives will only
report the Interactable GameObject.
These additional elements make it easy to identify the drive and
type based on the tag and string of the found colliding object.
> feat(prefab): add tag and string identifiers to drive elements

- Documentation/API/AngularDriver/AngularDriveTag.md
- Documentation/API/AngularDriver/AngularDriveTag.md.meta
- Documentation/API/AngularDriver/README.md
- Documentation/API/LinearDriver/LinearDriveTag.md
- Documentation/API/LinearDriver/LinearDriveTag.md.meta
- Documentation/API/LinearDriver/README.md
- Editor/Interactables.meta
- Editor/Interactables/ControllableCreatorEditorWindow.cs
- Editor/Interactables/ControllableCreatorEditorWindow.cs.meta
- Editor/Tilia.Interactions.Controllables.Unity.Editor.asmdef
The new Controllable Creator window makes it easier to turn an existing
scene mesh into a controllable by automatically adding the selected
prefab and nesting the mesh in the appropriate location.
> feat(Editor): add controllable creator window

- Editor/Interactables/ControllableCreatorEditorWindow.cs
The Controllable Creator now only applies the original mesh position
to the new controllable prefab and the rotation, scale of the mesh
stay on the original mesh. This is because controllables that have
external rotations and scales will warp the object inside so the
mesh is the thing that needs rotating and scaling.
> fix(Editor): only apply position when auto creating controllable

- Runtime/Prefabs/PhysicsJoint/Interactions.AngularJointDrive.prefab
- Runtime/Prefabs/PhysicsJoint/Interactions.LinearJointDrive.prefab
- Runtime/Prefabs/Transform/Interactions.AngularTransformDrive.prefab
- Runtime/Prefabs/Transform/Interactions.LinearTransformDrive.prefab
The new Zinnia BaseGameObjectSelector when added to a GameObject will
cause the GameObject to be selected when the mesh is clicked in the
Unity scene view. This has been added to the facade to ensure the
facade is selected when the mesh is clicked.
> feat(prefabs): add selection base component to facade

- Documentation/API/AngularDriver/AngularDrive.md
- Documentation/API/AngularDriver/AngularDriveFacade.md
- Documentation/API/AngularDriver/AngularJointDrive.md
- Documentation/API/AngularDriver/AngularTransformDrive.md
- Documentation/API/Driver/Drive-2.md
- Documentation/API/Driver/DriveFacade-2.md
- Documentation/API/LinearDriver/LinearDrive.md
- Documentation/API/LinearDriver/LinearDriveFacade.md
- Documentation/API/LinearDriver/LinearJointDrive.md
- Documentation/API/LinearDriver/LinearTransformDrive.md
The new grabbed/ungrabbed drag values were missing from the docs.
They have now been auto generated to include them.
> fix(Documentation): add missing API docs

- Runtime/SharedResources/Scripts/Driver/Drive.cs
The GrabbedDrag and UngrabbedDrag values were not being propagated to
the relevant Float event proxy when the controllable was enabled as
the code to set their values was not being called until the property
was changed.
This fix ensures the data is propagated in the OnEnable call.
> fix(Drive): ensure the grabbed/ungrabbed drag values are set on enable - fixes #200

- Runtime/Prefabs/PhysicsJoint/Interactions.AngularJointDrive.prefab
- Runtime/Prefabs/PhysicsJoint/Interactions.LinearJointDrive.prefab
- Runtime/Prefabs/Transform/Interactions.AngularTransformDrive.prefab
- Runtime/Prefabs/Transform/Interactions.LinearTransformDrive.prefab
The drag settings for the Angular Joint Drive prefab have been updated so they are firstly more inline with the transform drive and so the grabbed drag is not so high as this will just refuse to work on certain refresh rate settings as physics is tied to the headset refresh rate.
> fix(Prefabs): provide better angular joint drive drag settings

- Runtime/SharedResources/Scripts/AngularDriver/AngularJointDrive.cs
- Runtime/SharedResources/Scripts/LinearDriver/LinearJointDrive.cs
- Runtime/SharedResources/Scripts/LinearDriver/LinearTransformDrive.cs
There is no point in applying a velocity to a kinematic rigidbody as it can accept no forces anyway, so these checks just make sure the rigidbody is not kinematic before applying velocities to it.
> fix(Drive): prevent applying velocies to a kinematic rigidbody

- Documentation/API/AngularDriver/AngularDrive.md
- Documentation/API/AngularDriver/AngularJointDrive.md
- Documentation/API/AngularDriver/AngularTransformDrive.md
- Documentation/API/Driver/Drive-2.md
- Documentation/API/LinearDriver/LinearDrive.md
- Documentation/API/LinearDriver/LinearJointDrive.md
- Documentation/API/LinearDriver/LinearTransformDrive.md
- Runtime/Prefabs/PhysicsJoint/Interactions.AngularJointDrive.prefab
- Runtime/Prefabs/Transform/Interactions.AngularTransformDrive.prefab
- Runtime/SharedResources/Scripts/Driver/Drive.cs
There was an issue where a high initial drive speed would mean a drive (specifically a joint drive) would never reach the initial target value as it would just keep overshooting and a small threshold was never enough to ensure it could reach the target. A larger threshold would just cause drive issues.
The solution is to ensure the initial drive speed starts high, but over each frame reduces by a certain amount (e.g. by half each frame) and therefore the fidelity of the drive will get tighter with each frame meaning it slows down but will have an increasing higher chance of reaching its initial target.
> fix(Drive): decrease initial drive speed each frame for accuracy - fixes #223

- Runtime/Prefabs/PhysicsJoint/Interactions.AngularJointDrive.prefab
- Runtime/Prefabs/PhysicsJoint/Interactions.LinearJointDrive.prefab
- Runtime/Prefabs/Transform/Interactions.AngularTransformDrive.prefab
- Runtime/Prefabs/Transform/Interactions.LinearTransformDrive.prefab
The previous commit updated the prefabs for Unity 2021 which struggle to be backward compatible. The prefabs should always be in the 2018 format as this is the earliest version of Unity that is supported.
> fix(Prefabs): ensure prefabs are built for Unity 2018

- Documentation/API/AngularDriver/AngularDrive.md
- Documentation/API/AngularDriver/AngularJointDrive.md
- Documentation/API/AngularDriver/AngularTransformDrive.md
- Documentation/API/Driver/Drive-2.md
- Documentation/API/LinearDriver/LinearDrive.md
- Documentation/API/LinearDriver/LinearJointDrive.md
- Documentation/API/LinearDriver/LinearTransformDrive.md
- Runtime/SharedResources/Scripts/Driver/Drive.cs
The Target Value Reached threshold is usually larger for an auto moving drive so it cannot overshoot, but for a grabbed drive the target threshold can tend to be too large causing a jitter when the grabbed drive is moved to the extremes.
This adds a new threshold value for when the drive is grabbed so it can be even more refined for a better experience.
> feat(Drive): add grabbed target threshold

- Documentation/API/AngularDriver/AngularTransformDrive.md
- Runtime/Prefabs/Transform/Interactions.AngularTransformDrive.prefab
- Runtime/SharedResources/Scripts/AngularDriver/AngularTransformDrive.cs
The AngularTransformDrive can have the
`FollowRotateAroundAngularVelocity` Follow Tracking setting but it never automatically set up the axis the drive was set on.
This now allows for it to automatically set up the axis based on what axis is selected on the Drive Facade.
> feat(AngularDriver): auto set up twist axis settings

- Runtime/SharedResources/Scripts/LinearDriver/LinearDrive.cs
- Runtime/SharedResources/Scripts/LinearDriver/LinearJointDrive.cs
The isActiveAndEnabled call has been replaced with CheckIsActiveAndEnabled as this is more consistent.
> feat(Drive): replace isActiveAndEnabled

- Editor/Interactables/LinearDriveFacadeEditor.cs
If the ZINNIA_IGNORE_CUSTOM_INSPECTOR_EDITOR ifdef is set then the custom editor must also be disabled otherwise an error will occur.
> fix(Editor): disable custom inspector if ignore custom editor is set
